stages:
    - deploy

deploy:
    stage: "deploy"
    only:
        - master
    tags:
      - hurom-app
    environment:
        name: production
        url: https://hurom.cz
    script:
        - cp -rv ./* /var/www/hurom/client/
        - cd /var/www/hurom/server/ && sudo docker-compose down
        - cd /var/www/hurom/server/ && sudo docker-compose up -d
