stages:
    - build
    - deploy

build:
    stage: build
    tags:
      - hurom-app
    script:
      - echo "Building deploy package"
      - npm install
      - CI= npm run build
      - echo "Build successful"
deploy:
    stage: deploy
    tags:
      - hurom-app
    script:
        - echo "Deploying to server"
        - cp -rv ./ /var/www/hurom/client/
        - echo "Deployed"
    environment:
        name: production
        url: https://hurom.cz
    only:
        - master
