stages:
    - deploy

deploy:
    stage: deploy
    tags:
      - hurom-next
    script:
        - echo "Deploying to server"
        - cp -rv ./ /var/www/hurom/client/
        - cd /var/www/hurom/client/ && sudo docker-compose down
        - cd /var/www/hurom/client/ && sudo docker-compose build
        - cd /var/www/hurom/client/ && sudo docker-compose up -d
        - echo "Deployed"
    environment:
        name: production
        url: https://hurom.cz
    only:
        - master
