version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hurom-client
    hostname: hurom-client
    restart: always
    env_file: .env
    environment:
      - APP_API=$APP_API
    ports:
      - "3000:3000"
    networks:
      - huromClient

networks:
  huromClient:
